"""quiz add page_size

Revision ID: 9ebae112e3ca
Revises: 6be09d6dc59c
Create Date: 2025-03-30 18:35:18.058276+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ebae112e3ca'
down_revision: Union[str, None] = '6be09d6dc59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attempt_seed_quiz_attempt_id_fkey', 'attempt_seed', type_='foreignkey')
    op.create_foreign_key(None, 'attempt_seed', 'quiz_attempt', ['quiz_attempt_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('choice_question_id_fkey', 'choice', type_='foreignkey')
    op.create_foreign_key(None, 'choice', 'question', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('question_quiz_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'quiz', ['quiz_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('quiz', sa.Column('page_size', sa.Integer(), nullable=True))
    op.drop_constraint('quiz_created_by_fkey', 'quiz', type_='foreignkey')
    op.create_foreign_key(None, 'quiz', 'user', ['created_by'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('quiz_attempt_quiz_id_fkey', 'quiz_attempt', type_='foreignkey')
    op.drop_constraint('quiz_attempt_user_id_fkey', 'quiz_attempt', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempt', 'quiz', ['quiz_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'quiz_attempt', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('quiz_attempt_question_question_id_fkey', 'quiz_attempt_question', type_='foreignkey')
    op.drop_constraint('quiz_attempt_question_selected_choice_id_fkey', 'quiz_attempt_question', type_='foreignkey')
    op.drop_constraint('quiz_attempt_question_quiz_attempt_id_fkey', 'quiz_attempt_question', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempt_question', 'quiz_attempt', ['quiz_attempt_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'quiz_attempt_question', 'question', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'quiz_attempt_question', 'choice', ['selected_choice_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_attempt_question', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempt_question', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempt_question', type_='foreignkey')
    op.create_foreign_key('quiz_attempt_question_quiz_attempt_id_fkey', 'quiz_attempt_question', 'quiz_attempt', ['quiz_attempt_id'], ['id'])
    op.create_foreign_key('quiz_attempt_question_selected_choice_id_fkey', 'quiz_attempt_question', 'choice', ['selected_choice_id'], ['id'])
    op.create_foreign_key('quiz_attempt_question_question_id_fkey', 'quiz_attempt_question', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'quiz_attempt', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempt', type_='foreignkey')
    op.create_foreign_key('quiz_attempt_user_id_fkey', 'quiz_attempt', 'user', ['user_id'], ['id'])
    op.create_foreign_key('quiz_attempt_quiz_id_fkey', 'quiz_attempt', 'quiz', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.create_foreign_key('quiz_created_by_fkey', 'quiz', 'user', ['created_by'], ['id'])
    op.drop_column('quiz', 'page_size')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_quiz_id_fkey', 'question', 'quiz', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'choice', type_='foreignkey')
    op.create_foreign_key('choice_question_id_fkey', 'choice', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'attempt_seed', type_='foreignkey')
    op.create_foreign_key('attempt_seed_quiz_attempt_id_fkey', 'attempt_seed', 'quiz_attempt', ['quiz_attempt_id'], ['id'])
    # ### end Alembic commands ###
